config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "users#index"

  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:create, :new, :destroy] 
      resources :likes, only: [:create]
    end
  end

  # API ROUTES
  namespace :api do 
    namespace :v1 do 
      resources :users do 
        resources :posts do 
          resources :comments 
          resources :likes
        end
      end
    end
  end
   

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, allow_blank: false
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
     before_action :find_user, except: %i[index]


     def index
          @users = User.all.order(:id)
          render json: @users, status: :ok
     end

     def show 
          render json: @user, status: :ok
     end

     private

     def find_user
          @user = User.find_by_id!(params[:id])
     rescue ActiveRecord::RecordNotFound
          render json: { message: 'User not found'}, status: :not_found
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<section class="show-user">
   <div class="card" style="width: 18rem;">
      <ul class="users_list">
          <% @users.each do |user| %>
               <li class = 'user' >
               <% if user.photo %>
                    <img class="card-img-top" src='<%= user.photo %>' alt='<%= user.name %> thumbnail' />
               <% end %>
                    <div class='card-body'>
                         <h5> Username: <%= user.name%></h5>
                         <p class="card-text">Number of Posts: <%= user.posts_counter %></p>
                          <%= link_to 'View user posts', user_path(user), class: "btn btn-primary text-center"  %>
                    </div>
               </li>
          <% end %>
     </ul>
     </div>
</section>

app/views/users/show.html.erb
<section class="container">
  <div class="user-box">
  <% if @user.photo %>
  <img class="card-img-top" src='<%= @user.photo %>' alt='<%= @user.name %> thumbnail' />
<% end %>
    <div class="user-info">
      <p class="user-name"><%= @user.name %></p>
      <p class="user-post">Number of posts: <%= @user.posts_counter%></p>
    </div>
  </div>
  <p class="user-bio"><%= @user.bio %></p>
  <% @user.three_most_recent_post.each do |post| %>
    <%= link_to user_post_path(@user.id, post.id) do %>
      <div class="user-recent-post">
        <p class="post-title"><strong>Post</strong> : <%= post.title %></p>
        <p class="post-text"><%= post.text %></p>
        <h3 class="counters">Comments: <%= post.comments_counter %> <h3>
         <h3> Likes: <%= post.likes_counter %> <h3 >
          
          </div>
        <% end %>
      <% end %>
      <div class="button-user">
        <button class="button">
          <%= link_to "See all posts", user_posts_path(@user), class:"text-button" %>
        </button>
      </div>
    </section>