config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "users#index"

  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:create, :new, :destroy] 
      resources :likes, only: [:create]
    end
  end

  # API ROUTES
  namespace :api do 
    namespace :v1 do 
      resources :users do 
        resources :posts do 
          resources :comments 
          resources :likes
        end
      end
    end
  end
   

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: :post_id, dependent: :delete_all
  has_many :comments, foreign_key: :post_id, dependent: :delete_all

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  # validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  # validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.update(posts_counter: author.posts.all.length)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
     # before_action :authorize_request
     before_action :find_user


     def index 
          post = Post.where(author_id: params[:user_id])
          # posts = user.post 

          if post 
               render json: post, status: :ok 
          else
               render json: { message: 'No post found'}, status: :not_found
     end
end

          def show
               @post = @user.posts.find_by_id!(params[:id])
               render json: @post, status: :ok 
               rescue ActiveRecord::RecordNotFound
                    render json: { message: 'Post not found'}, status: :not_found
          end

     private

     def find_user
          @user = User.find(params[:user_id])
          rescue ActiveRecord::RecordNotFound
               render json: { message: 'User not found'}, status: :not_found
          end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.author.decrement!(:posts_counter)
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post has benn created successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'Error: Post was not created !!'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<section>
  <div class='single-user'>
    <div class='user-photo'>
      <img src='<%= @user.photo %>' alt='<%= @user.name %> thumbnail' />
    </div>
    <div class='user-name'>
      <h2><%= @user.name %></h2>
      <p>Number of Posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class='user-posts'>
    <% @user.posts.each do |post| %>
      <div class='list-posts'>
        <h5><%= link_to post.title, user_post_path(@user, post) %></h5>
        <p><%= post.text %></p>
        <span class='like-comment'>
          Comments: <%= post.comments_counter || 0 %>, 
          Likes: <%= post.likes_counter || 0 %> 
        </span>
      </div>
      <ul class='post-comment'>
        <% if post.five_recent_comments %>
        <% post.five_recent_comments.each do |comment| %>
          <li><%= comment.author_id %>: <%= comment.text %></li>
          <% end %>
        <% else %>
          <% post.five_recent_comments.each do |comment| %>
            <li><%= comment.users.name %>: <%= comment.text %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<section class="container">
<p class="post-title"> Add New Post :</p>
<%= form_with model: @post, url: user_posts_path do |f| %>
     <div>
     <%= f.label :title %> <br>
     <%= f.text_field :title %>
     </div>

     <div>
     <%= f.label :text %> <br>
     <%= f.text_field :text %>
     </div>
     <br>
     <div>
     <%= f.submit "Submit Post" %>
     </div>
<% end %>

</section>

app/views/posts/show.html.erb
<section class="container">
  <div class="post-info">
    <div class="post-title-box">
      <p class="post-title">Post : <%= @post.title %> by <%= @post.author.name %></p>
     
    </div>
    <p><%= @post.text %></p>
     <p class="comment-text">Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>

     <div class = 'd-flex'>

     <% if can? :destroy , @post %>
     <%= button_to 'Delete Post', user_post_path(@user, @post), method: :delete, class: "btn btn-danger mx-3" %>
     <% end %>

     <%= render "likes/add_like"%>
     </div>


  </div>
  <div class="comment-info">
    <% @post.five_recent_comments.each do |comment| %>
      <div>
        <p>
          <span>
            <%= comment.author.name %>:
          </span>
          <span>
            <%= comment.text %>
          </span>
        </p>
      </div>
      <% if can? :destroy , comment %>
      <%= button_to 'Delete comment', user_post_comment_path(@user , @post , comment), method: :delete, class: "btn btn-dark" %>
      <% end %>

      
    <% end %>
  </div>
  <%= render "comments/add_comment" %>
</section>